# https://travis-ci.org/tornadoweb/tornado
language: python
python:
    - 3.5
    - 3.6

install:
    - pip install -r requirements/base.txt

script:
    - pylint todo

sudo: false

matrix:
    fast_finish: true